title:              Mohan S.
email:              mohanadassan@gmail.com
description:        My Data Science Portfolio
author:             Mohan 
baseurl:            ""
url:                "https://mohan0101data.github.io"

# Social Profiles
twitter_username:   Mohan59400039   
github_username:    mohan0101data
facebook_username:  
instagram_username:  
linkedin_username:  mohanadassan-subramaniam-779320109

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
